// Auto-generated by Animation Forge
// Character: corn

using UnityEngine;

public static class CornAnimatorParams
{
    // Parameters
    public const string SPEED = "Speed";
    public const string ISGROUNDED = "IsGrounded";
    public const string ATTACKTRIGGER = "AttackTrigger";
    public const string HURTTRIGGER = "HurtTrigger";
    public const string DEATHTRIGGER = "DeathTrigger";

    // State Names
    public const string STATE_DEATH = "death";
    public const string STATE_BLOCK = "block";
    public const string STATE_HURT = "hurt";
    public const string STATE_GUARD = "guard";
    public const string STATE_JUMP = "jump";
    public const string STATE_KNEEL = "kneel";
    public const string STATE_WALK = "walk";
}
