// Auto-generated by Animation Forge — process_character.py
// Character: red_player

using UnityEngine;

public static class RedPlayerAnimatorParams
{
    public const string SPEED = "Speed";
    public const string ISGROUNDED = "IsGrounded";
    public const string ISGUARDING = "IsGuarding";
    public const string ATTACKTRIGGER = "AttackTrigger";
    public const string HURTTRIGGER = "HurtTrigger";
    public const string DEATHTRIGGER = "DeathTrigger";
    public const string JUMPTRIGGER = "JumpTrigger";
    public const string DASHTRIGGER = "DashTrigger";
    public const string KNEELTRIGGER = "KneelTrigger";

    public const string STATE_ATTACK_1 = "attack_1";
    public const string STATE_ATTACK_2 = "attack_2";
    public const string STATE_ATTACK_3 = "attack_3";
    public const string STATE_BLOCK = "block";
    public const string STATE_DASH = "dash";
    public const string STATE_DEATH = "death";
    public const string STATE_FALL = "fall";
    public const string STATE_GUARD = "guard";
    public const string STATE_HURT = "hurt";
    public const string STATE_IDLE = "idle";
    public const string STATE_JUMP = "jump";
    public const string STATE_LAND = "land";
    public const string STATE_RUN = "run";
    public const string STATE_WALK = "walk";
}
