// Auto-generated by Animation Forge
// Character: tomato_fighter

using UnityEngine;

public static class TomatoFighterAnimatorParams
{
    // Parameters
    public const string SPEED = "Speed";
    public const string ISGROUNDED = "IsGrounded";
    public const string ATTACKTRIGGER = "AttackTrigger";
    public const string HURTTRIGGER = "HurtTrigger";
    public const string DEATHTRIGGER = "DeathTrigger";

    // State Names
    public const string STATE_IDLE = "idle";
    public const string STATE_WALK = "walk";
    public const string STATE_RUN = "run";
    public const string STATE_JUMP = "jump";
    public const string STATE_LAND = "land";
}
